version: '3.8'
services:
  postgres:
    image: postgres:10.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5438:5432"
    volumes:
      - ./postgres:/postgres-data
  authentication:
    build: ./Authentication
    container_name: authentication
    ports:
      - 9090:9090
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - authnetwork
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./db:/db
    ports:
      - "27017"
    restart: unless-stopped
  driverlocation:
    build: ./DriverLocationAPI
    container_name: driverlocation
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mongodb
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password

networks:
  authnetwork:
  